const conn = require("../conn");
const { INTEGER, DATE, DECIMAL, UUID, STRING, JSON, BOOLEAN } = conn.Sequelize;

const CombinedUpload = conn.define("combinedUpload", {
  userId: {
    type: UUID,
    allowNull: false,
    references: {
      model: "agentusers",
      key: "id",
    },
  },
  name: {
    type: STRING,
    allowNull: false,
    comment: "User-friendly name for the combined upload",
  },
  uploadIds: {
    type: JSON,
    allowNull: false,
    comment: "Array of FinancialUpload IDs that are combined",
  },
  createdAt: {
    type: DATE,
    defaultValue: conn.Sequelize.NOW,
  },
  monthCount: {
    type: INTEGER,
    allowNull: false,
    comment: "Total months across all uploads",
  },
  startDate: {
    type: DATE,
    allowNull: false,
    comment: "Earliest transaction date across all uploads",
  },
  endDate: {
    type: DATE,
    allowNull: false,
    comment: "Latest transaction date across all uploads",
  },
  totalTransactions: {
    type: INTEGER,
    defaultValue: 0,
  },
  totalMonthlyAverage: {
    type: DECIMAL(10, 2),
    defaultValue: 0,
    comment: "Combined monthly average across all sources",
  },
  sourceBreakdown: {
    type: JSON,
    allowNull: true,
    comment: "Breakdown by source file (filename, monthly avg, transaction count)",
  },
  calculationLog: {
    type: JSON,
    allowNull: true,
  },
  isAutoGenerated: {
    type: BOOLEAN,
    defaultValue: false,
    comment: "True if created from multi-file upload, false if manually combined",
  },
});

module.exports = CombinedUpload;
