const questionData = [
  // ---------- JavaScript ----------
  {
    questionNumber: 1,
    category: "JavaScript",
    question: "What is the output of the following code? console.log(typeof null);",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "'null'",
    answerTwo: "'object'",
    answerThree: "'undefined'",
    answerFour: "'number'",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 2,
    category: "JavaScript",
    question: "Which of the following is NOT a primitive type in JavaScript?",
    correctAnswerArray: [false, false, false, true, false],
    answerOne: "String",
    answerTwo: "Number",
    answerThree: "Symbol",
    answerFour: "Object",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 3,
    category: "JavaScript",
    question: "What does the === operator compare?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "Both value and type",
    answerTwo: "Value only",
    answerThree: "Type only",
    answerFour: "Memory address only",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 4,
    category: "JavaScript",
    question: "What does NaN === NaN evaluate to?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "true",
    answerTwo: "A TypeError is thrown",
    answerThree: "false",
    answerFour: "undefined",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 5,
    category: "JavaScript",
    question: "What does typeof NaN return?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "'NaN'",
    answerTwo: "'number'",
    answerThree: "'undefined'",
    answerFour: "'object'",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 6,
    category: "JavaScript",
    question: "What is the main difference between let and var?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "let is block-scoped, var is function-scoped",
    answerTwo: "var is block-scoped, let is function-scoped",
    answerThree: "let cannot be reassigned",
    answerFour: "There is no difference",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 7,
    category: "JavaScript",
    question: "What happens when you read a var variable before its declaration line runs?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "A ReferenceError is thrown",
    answerTwo: "It evaluates to undefined",
    answerThree: "It evaluates to null",
    answerFour: "It evaluates to the value assigned later",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 8,
    category: "JavaScript",
    question: "What happens when you read a let variable before its declaration line runs?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "A ReferenceError is thrown",
    answerTwo: "It evaluates to undefined",
    answerThree: "It evaluates to null",
    answerFour: "It works normally",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 9,
    category: "JavaScript",
    question: "An array is declared with const. What happens when you call push() on it?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "A TypeError is thrown",
    answerTwo: "A SyntaxError is thrown",
    answerThree: "It works — const prevents reassignment, not mutation",
    answerFour: "The array is silently copied first",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 10,
    category: "JavaScript",
    question: "What happens when you reassign a variable declared with const?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "A TypeError is thrown",
    answerTwo: "The reassignment silently fails",
    answerThree: "It works normally",
    answerFour: "The variable becomes undefined",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 11,
    category: "JavaScript",
    question: "What is a closure?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "A function that calls itself",
    answerTwo: "A function bundled with references to its surrounding lexical scope",
    answerThree: "A function with no parameters",
    answerFour: "An object that contains only functions",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 12,
    category: "JavaScript",
    question: "What is the output of [1, 2, 3].map(x => x * 2)?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "[2, 4, 6]",
    answerTwo: "[1, 2, 3]",
    answerThree: "6",
    answerFour: "undefined",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 13,
    category: "JavaScript",
    question: "What does Array.prototype.map return?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "The original array, modified in place",
    answerTwo: "A single accumulated value",
    answerThree: "A new array the same length as the original",
    answerFour: "undefined",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 14,
    category: "JavaScript",
    question: "What does Array.prototype.filter return?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "The first element that passes the test",
    answerTwo: "A new array containing only the elements that pass the test",
    answerThree: "true if any element passes the test",
    answerFour: "The original array with failing elements set to null",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 15,
    category: "JavaScript",
    question: "What is Array.prototype.reduce typically used for?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "Combining all elements into a single accumulated value",
    answerTwo: "Removing elements that fail a test",
    answerThree: "Shrinking the array's memory footprint",
    answerFour: "Sorting the array in descending order",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 16,
    category: "JavaScript",
    question: "What does Array.prototype.find return when no element matches?",
    correctAnswerArray: [false, false, false, true, false],
    answerOne: "null",
    answerTwo: "-1",
    answerThree: "An empty array",
    answerFour: "undefined",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 17,
    category: "JavaScript",
    question: "Which array method removes the last element and returns it?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "shift()",
    answerTwo: "pop()",
    answerThree: "slice()",
    answerFour: "splice()",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 18,
    category: "JavaScript",
    question: "Which array method adds one or more elements to the beginning of an array?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "push()",
    answerTwo: "pop()",
    answerThree: "unshift()",
    answerFour: "shift()",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 19,
    category: "JavaScript",
    question: "Which of these array methods mutates the original array?",
    correctAnswerArray: [false, false, false, true, false],
    answerOne: "map()",
    answerTwo: "filter()",
    answerThree: "concat()",
    answerFour: "sort()",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 20,
    category: "JavaScript",
    question: "What does [10, 20, 30, 40].slice(1, 3) return?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "[20, 30]",
    answerTwo: "[20, 30, 40]",
    answerThree: "[10, 20, 30]",
    answerFour: "[30]",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 21,
    category: "JavaScript",
    question: "What does Array.prototype.includes return?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "The index of the matching element",
    answerTwo: "true or false",
    answerThree: "The matching element itself",
    answerFour: "A new array of matches",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 22,
    category: "JavaScript",
    question: "What is the most reliable way to check whether a value is an array?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "typeof value === 'array'",
    answerTwo: "value instanceof Object",
    answerThree: "Array.isArray(value)",
    answerFour: "value.length !== undefined",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 23,
    category: "JavaScript",
    question: "What does typeof [] return?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "'object'",
    answerTwo: "'array'",
    answerThree: "'list'",
    answerFour: "'undefined'",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 24,
    category: "JavaScript",
    question: "What is the result of '1' + 2 in JavaScript?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "3",
    answerTwo: "'12'",
    answerThree: "12",
    answerFour: "NaN",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 25,
    category: "JavaScript",
    question: "What is the result of '5' - 2 in JavaScript?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "3",
    answerTwo: "'52'",
    answerThree: "NaN",
    answerFour: "'3'",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 26,
    category: "JavaScript",
    question: "What does '0' == false evaluate to, and why?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "true — both sides are coerced to the number 0",
    answerTwo: "false — a string can never equal a boolean",
    answerThree: "It throws a TypeError",
    answerFour: "undefined",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 27,
    category: "JavaScript",
    question: "What do null == undefined and null === undefined evaluate to, respectively?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "true and true",
    answerTwo: "true and false",
    answerThree: "false and false",
    answerFour: "false and true",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 28,
    category: "JavaScript",
    question: "What does 0.1 + 0.2 === 0.3 evaluate to?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "true",
    answerTwo: "It throws a RangeError",
    answerThree: "false — binary floating-point math is imprecise",
    answerFour: "true, but only in strict mode",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 29,
    category: "JavaScript",
    question: "What does Number('abc') return?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "NaN",
    answerTwo: "0",
    answerThree: "undefined",
    answerFour: "It throws a TypeError",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 30,
    category: "JavaScript",
    question: "What does parseInt('12px') return?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "NaN",
    answerTwo: "12",
    answerThree: "0",
    answerFour: "It throws an error",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 31,
    category: "JavaScript",
    question: "Which of these values is truthy?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "0 (the number zero)",
    answerTwo: "'' (empty string)",
    answerThree: "'0' (a string containing zero)",
    answerFour: "null",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 32,
    category: "JavaScript",
    question: "How do you enable strict mode?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "Set window.strict = true",
    answerTwo: "Add 'use strict'; at the top of a file or function",
    answerThree: "Run the file with the --strict flag",
    answerFour: "Wrap the code in a strict() block",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 33,
    category: "JavaScript",
    question: "Which characters delimit a template literal?",
    correctAnswerArray: [false, false, false, true, false],
    answerOne: "Single quotes",
    answerTwo: "Double quotes",
    answerThree: "Forward slashes",
    answerFour: "Backticks",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 34,
    category: "JavaScript",
    question: "What does the spread operator (...) do when used with an array?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "Expands the array into its individual elements",
    answerTwo: "Flattens all nested arrays recursively",
    answerThree: "Creates a deep copy of every element",
    answerFour: "Sorts the elements before copying them",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 35,
    category: "JavaScript",
    question: "What does const { name } = user; do?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "Creates an object named name containing user",
    answerTwo: "Creates a variable name set to user.name",
    answerThree: "Renames the user object to name",
    answerFour: "Throws a SyntaxError",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 36,
    category: "JavaScript",
    question: "Which syntax gives a function parameter a default value?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "function greet(name || 'friend') {}",
    answerTwo: "function greet(name: 'friend') {}",
    answerThree: "function greet(name = 'friend') {}",
    answerFour: "function greet(default name 'friend') {}",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 37,
    category: "JavaScript",
    question: "How is 'this' determined inside an arrow function?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "It is inherited from the enclosing lexical scope",
    answerTwo: "It is bound to the object that calls the function",
    answerThree: "It is always the global object",
    answerFour: "It is always undefined",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 38,
    category: "JavaScript",
    question: "What does Function.prototype.bind do?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "Immediately calls the function with a given 'this'",
    answerTwo: "Returns a new function with 'this' permanently set",
    answerThree: "Attaches the function to the global object",
    answerFour: "Prevents the function from being called twice",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 39,
    category: "JavaScript",
    question: "What is the difference between call() and apply()?",
    correctAnswerArray: [false, false, false, true, false],
    answerOne: "call() is asynchronous, apply() is synchronous",
    answerTwo: "apply() sets 'this', call() does not",
    answerThree: "They are identical in every way",
    answerFour: "apply() takes arguments as a single array, call() takes them individually",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 40,
    category: "JavaScript",
    question: "What does an async function always return?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "A Promise",
    answerTwo: "undefined",
    answerThree: "The awaited value directly",
    answerFour: "A callback function",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 41,
    category: "JavaScript",
    question: "What are the three states of a Promise?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "started, running, finished",
    answerTwo: "open, closed, errored",
    answerThree: "pending, fulfilled, rejected",
    answerFour: "queued, active, done",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 42,
    category: "JavaScript",
    question: "What does .catch() handle on a Promise chain?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "Only network errors",
    answerTwo: "Rejections and errors thrown earlier in the chain",
    answerThree: "Only syntax errors",
    answerFour: "Successful results",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 43,
    category: "JavaScript",
    question: "When does a finally block run?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "Always — whether or not an error was thrown",
    answerTwo: "Only when an error was thrown",
    answerThree: "Only when no error was thrown",
    answerFour: "Only when the catch block is missing",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 44,
    category: "JavaScript",
    question: "Which of these is a valid place to use the await keyword?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "Inside any regular function",
    answerTwo: "Inside an async function",
    answerThree: "Inside a synchronous for loop in any function",
    answerFour: "Inside a class constructor",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 45,
    category: "JavaScript",
    question: "When does the callback of setTimeout(fn, 0) actually run?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "Immediately, interrupting the current code",
    answerTwo: "Exactly 0 milliseconds later, in parallel",
    answerThree: "After the current synchronous code finishes executing",
    answerFour: "It never runs with a delay of 0",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 46,
    category: "JavaScript",
    question: "A resolved promise's .then callback and a setTimeout(fn, 0) callback are both queued. Which runs first?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "The promise callback — microtasks run before macrotasks",
    answerTwo: "The setTimeout callback — timers always have priority",
    answerThree: "Whichever was queued first",
    answerFour: "They run at the same time on separate threads",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 47,
    category: "JavaScript",
    question: "What is the difference between for...of and for...in?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "They are interchangeable",
    answerTwo: "for...of iterates values, for...in iterates property keys",
    answerThree: "for...in iterates values, for...of iterates property keys",
    answerFour: "for...of only works on objects",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 48,
    category: "JavaScript",
    question: "What happens when you add a duplicate value to a Set?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "It is ignored — a Set only stores unique values",
    answerTwo: "It throws a TypeError",
    answerThree: "Both copies are stored",
    answerFour: "The Set is converted to an array",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 49,
    category: "JavaScript",
    question: "What is one advantage of a Map over a plain object?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "Maps are always faster",
    answerTwo: "Maps can be serialized directly to JSON",
    answerThree: "Map keys can be any type, including objects",
    answerFour: "Maps automatically sort their keys alphabetically",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 50,
    category: "JavaScript",
    question: "What does Object.keys(obj) return?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "An array of the object's values",
    answerTwo: "An array of the object's own enumerable property names",
    answerThree: "An array of [key, value] pairs",
    answerFour: "The number of properties on the object",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 51,
    category: "JavaScript",
    question: "What does Object.freeze(obj) do?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "Prevents adding, removing, or changing the object's top-level properties",
    answerTwo: "Deep-freezes the object and everything nested inside it",
    answerThree: "Deletes all of the object's properties",
    answerFour: "Makes the object garbage-collected immediately",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 52,
    category: "JavaScript",
    question: "What does optional chaining (?.) do?",
    correctAnswerArray: [false, false, false, true, false],
    answerOne: "Retries the property access until it succeeds",
    answerTwo: "Converts null values to empty strings",
    answerThree: "Throws a friendlier error message",
    answerFour: "Returns undefined instead of throwing when the left side is null or undefined",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 53,
    category: "JavaScript",
    question: "When does the nullish coalescing operator (??) return its right-hand operand?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "When the left operand is any falsy value",
    answerTwo: "Only when the left operand is null or undefined",
    answerThree: "Only when the left operand is 0 or ''",
    answerFour: "Always",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 54,
    category: "JavaScript",
    question: "What does JSON.parse do?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "Converts a JSON string into a JavaScript value",
    answerTwo: "Converts a JavaScript value into a JSON string",
    answerThree: "Validates JSON without converting it",
    answerFour: "Fetches JSON from a URL",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 55,
    category: "JavaScript",
    question: "Which of these cannot appear as a value in valid JSON?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "null",
    answerTwo: "A nested object",
    answerThree: "undefined",
    answerFour: "An array",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 56,
    category: "JavaScript",
    question: "What does Array.from do?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "Removes an element from an array",
    answerTwo: "Creates a new array from an iterable or array-like value",
    answerThree: "Returns the first element of an array",
    answerFour: "Converts an array to a string",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 57,
    category: "JavaScript",
    question: "Which syntax declares a generator function?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "function* gen() {}",
    answerTwo: "generator gen() {}",
    answerThree: "async function gen() {}",
    answerFour: "function gen() yield {}",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 58,
    category: "JavaScript",
    question: "What is a Symbol?",
    correctAnswerArray: [false, false, false, true, false],
    answerOne: "A shorthand for string constants",
    answerTwo: "A special kind of number",
    answerThree: "A reference to a DOM element",
    answerFour: "A primitive guaranteed to be unique, often used as a property key",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 59,
    category: "JavaScript",
    question: "How many default exports can a single ES module have?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "Unlimited",
    answerTwo: "Two",
    answerThree: "One",
    answerFour: "Zero — default exports were removed in ES6",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 60,
    category: "JavaScript",
    question: "What is the difference between localStorage and sessionStorage?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "localStorage is cleared when the tab closes",
    answerTwo: "sessionStorage is cleared when the tab closes; localStorage persists",
    answerThree: "sessionStorage can store objects directly",
    answerFour: "localStorage is only available over HTTPS",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  // ---------- HTML ----------
  {
    questionNumber: 61,
    category: "HTML",
    question: "What does HTML stand for?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "Hyper Trainer Marking Language",
    answerTwo: "Home Tool Markup Language",
    answerThree: "Hyper Text Markup Language",
    answerFour: "Hyperlinks and Text Markup Language",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 62,
    category: "HTML",
    question: "What is the purpose of <!DOCTYPE html>?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "It tells the browser to render the page in standards mode as HTML5",
    answerTwo: "It imports the HTML standard library",
    answerThree: "It validates the page against the W3C servers",
    answerFour: "It is a comment and has no effect",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 63,
    category: "HTML",
    question: "Which of these is a semantic element?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "<div>",
    answerTwo: "<article>",
    answerThree: "<span>",
    answerFour: "<b>",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 64,
    category: "HTML",
    question: "Which attribute holds the destination URL of an <a> element?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "href",
    answerTwo: "src",
    answerThree: "link",
    answerFour: "url",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 65,
    category: "HTML",
    question: "How do you make a link open in a new tab?",
    correctAnswerArray: [false, false, false, true, false],
    answerOne: "newtab='true'",
    answerTwo: "rel='new'",
    answerThree: "window='blank'",
    answerFour: "target='_blank'",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 66,
    category: "HTML",
    question: "What is the purpose of the alt attribute on an <img>?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "It sets the image's tooltip text",
    answerTwo: "It provides alternative text for screen readers and when the image fails to load",
    answerThree: "It defines an alternate higher-resolution image",
    answerFour: "It is required for the image to display",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 67,
    category: "HTML",
    question: "What is the difference between <ul> and <ol>?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "<ol> is a numbered list, <ul> is a bulleted list",
    answerTwo: "<ul> is a numbered list, <ol> is a bulleted list",
    answerThree: "<ul> can only contain links",
    answerFour: "They are identical",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 68,
    category: "HTML",
    question: "Which element defines a row in a table?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "<td>",
    answerTwo: "<row>",
    answerThree: "<tr>",
    answerFour: "<th>",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 69,
    category: "HTML",
    question: "Which element defines a header cell in a table?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "<td>",
    answerTwo: "<th>",
    answerThree: "<thead>",
    answerFour: "<header>",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 70,
    category: "HTML",
    question: "Which input type gives built-in email format validation?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "<input type='email'>",
    answerTwo: "<input type='text' format='email'>",
    answerThree: "<input type='mail'>",
    answerFour: "<input validate='email'>",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 71,
    category: "HTML",
    question: "How does a <label> get associated with a specific input?",
    correctAnswerArray: [false, false, false, true, false],
    answerOne: "The label's name matches the input's name",
    answerTwo: "They must share the same class",
    answerThree: "The label's id matches the input's id",
    answerFour: "The label's for attribute matches the input's id",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 72,
    category: "HTML",
    question: "Which element creates a multi-line text input?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "<input type='text'>",
    answerTwo: "<textarea>",
    answerThree: "<input multiline>",
    answerFour: "<textbox>",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 73,
    category: "HTML",
    question: "Which element creates a dropdown list?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "<select>",
    answerTwo: "<dropdown>",
    answerThree: "<list>",
    answerFour: "<input type='dropdown'>",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 74,
    category: "HTML",
    question: "What is a key difference between form method='GET' and method='POST'?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "GET is more secure than POST",
    answerTwo: "POST appends the data to the URL",
    answerThree: "GET puts data in the URL query string; POST sends it in the request body",
    answerFour: "POST requests cannot send form data",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 75,
    category: "HTML",
    question: "Which of these elements is inline by default?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "<div>",
    answerTwo: "<span>",
    answerThree: "<p>",
    answerFour: "<section>",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 76,
    category: "HTML",
    question: "Which of these elements is block-level by default?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "<span>",
    answerTwo: "<a>",
    answerThree: "<p>",
    answerFour: "<strong>",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 77,
    category: "HTML",
    question: "Which element renders the largest heading by default?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "<h1>",
    answerTwo: "<h6>",
    answerThree: "<heading>",
    answerFour: "<head>",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 78,
    category: "HTML",
    question: "Which element inserts a line break?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "<lb>",
    answerTwo: "<br>",
    answerThree: "<break>",
    answerFour: "<newline>",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 79,
    category: "HTML",
    question: "What does <meta charset='UTF-8'> do?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "Declares the character encoding of the document",
    answerTwo: "Sets the document language to English",
    answerThree: "Compresses the page with UTF-8 compression",
    answerFour: "Enables emoji support only",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 80,
    category: "HTML",
    question: "Why do responsive sites include <meta name='viewport' content='width=device-width, initial-scale=1'>?",
    correctAnswerArray: [false, false, false, true, false],
    answerOne: "It loads a mobile-specific stylesheet",
    answerTwo: "It blocks zooming on mobile devices",
    answerThree: "It detects the user's device model",
    answerFour: "It makes the page width match the device width instead of a zoomed-out desktop layout",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 81,
    category: "HTML",
    question: "What does the defer attribute on a <script> tag do?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "Skips loading the script on slow connections",
    answerTwo: "Downloads in parallel and runs the script after the HTML is fully parsed, in order",
    answerThree: "Runs the script before any HTML is parsed",
    answerFour: "Only loads the script when the user scrolls to it",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 82,
    category: "HTML",
    question: "What does the async attribute on a <script> tag do?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "Makes every function in the script asynchronous",
    answerTwo: "Guarantees scripts run in document order",
    answerThree: "Downloads in parallel and runs as soon as it's ready, with no order guarantee",
    answerFour: "Delays the script until all images load",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 83,
    category: "HTML",
    question: "How do you attach an external stylesheet to a page?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "<link rel='stylesheet' href='styles.css'>",
    answerTwo: "<style src='styles.css'>",
    answerThree: "<script rel='stylesheet' href='styles.css'>",
    answerFour: "<css href='styles.css'>",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 84,
    category: "HTML",
    question: "What kind of content belongs in the <head> element?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "The page's main heading",
    answerTwo: "Metadata like the title, charset, and stylesheet links — not visible page content",
    answerThree: "The site's navigation bar",
    answerFour: "Anything that should appear at the top of the page",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 85,
    category: "HTML",
    question: "What are data-* attributes for?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "Storing custom data on an element, readable from JavaScript",
    answerTwo: "Connecting the element to a database",
    answerThree: "Improving SEO rankings",
    answerFour: "Encrypting form values",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 86,
    category: "HTML",
    question: "What is the default type of a <button> inside a form?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "button",
    answerTwo: "reset",
    answerThree: "submit",
    answerFour: "It has no default type",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 87,
    category: "HTML",
    question: "What does an <iframe> do?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "Draws vector graphics",
    answerTwo: "Embeds another HTML page inside the current page",
    answerThree: "Creates a floating image",
    answerFour: "Defines a reusable template",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 88,
    category: "HTML",
    question: "Which element semantically marks text as important?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "<strong>",
    answerTwo: "<b>",
    answerThree: "<important>",
    answerFour: "<big>",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 89,
    category: "HTML",
    question: "Which element semantically marks emphasized text?",
    correctAnswerArray: [false, false, false, true, false],
    answerOne: "<i>",
    answerTwo: "<italic>",
    answerThree: "<accent>",
    answerFour: "<em>",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 90,
    category: "HTML",
    question: "What is the difference between an id and a class?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "Classes must be unique; ids can repeat",
    answerTwo: "An id must be unique on the page; a class can be reused on many elements",
    answerThree: "ids are for CSS only; classes are for JavaScript only",
    answerFour: "There is no difference",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  // ---------- CSS ----------
  {
    questionNumber: 91,
    category: "CSS",
    question: "Which property changes the text color of an element?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "color",
    answerTwo: "text-color",
    answerThree: "font-color",
    answerFour: "text-style",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 92,
    category: "CSS",
    question: "Which is the correct CSS syntax?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "{body: color=black;}",
    answerTwo: "body {color: black;}",
    answerThree: "{body; color: black;}",
    answerFour: "body: color=black;",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 93,
    category: "CSS",
    question: "How do you write a comment in CSS?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "// this is a comment",
    answerTwo: "<!-- this is a comment -->",
    answerThree: "/* this is a comment */",
    answerFour: "# this is a comment",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 94,
    category: "CSS",
    question: "Which has the highest specificity?",
    correctAnswerArray: [false, false, false, true, false],
    answerOne: "An element selector (div)",
    answerTwo: "A class selector (.box)",
    answerThree: "An ID selector (#box)",
    answerFour: "An inline style attribute",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 95,
    category: "CSS",
    question: "A class rule and an ID rule set conflicting colors on the same element. Which wins?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "The ID rule — IDs have higher specificity than classes",
    answerTwo: "The class rule — classes have higher specificity than IDs",
    answerThree: "Whichever appears first in the stylesheet",
    answerFour: "The browser averages the two colors",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 96,
    category: "CSS",
    question: "From the inside out, what is the order of the box model layers?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "content, margin, border, padding",
    answerTwo: "content, padding, border, margin",
    answerThree: "padding, content, margin, border",
    answerFour: "margin, border, padding, content",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 97,
    category: "CSS",
    question: "What is the difference between margin and padding?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "Padding is space inside the border; margin is space outside it",
    answerTwo: "Margin is space inside the border; padding is space outside it",
    answerThree: "They are interchangeable",
    answerFour: "Padding only applies to text elements",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 98,
    category: "CSS",
    question: "What does box-sizing: border-box do?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "Adds a visible border around the box",
    answerTwo: "Makes padding and border add to the declared width",
    answerThree: "Makes the declared width include padding and border",
    answerFour: "Removes the element's margin",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 99,
    category: "CSS",
    question: "What is the difference between display: none and visibility: hidden?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "They behave identically",
    answerTwo: "display: none removes the element from the layout; visibility: hidden keeps its space",
    answerThree: "visibility: hidden removes the element from the layout; display: none keeps its space",
    answerFour: "display: none only works on images",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 100,
    category: "CSS",
    question: "An element has position: absolute. What is it positioned relative to?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "Its nearest positioned ancestor, or the document if there is none",
    answerTwo: "Always the browser viewport",
    answerThree: "Always its direct parent",
    answerFour: "The element that comes before it in the HTML",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 101,
    category: "CSS",
    question: "What is position: fixed positioned relative to?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "Its parent element",
    answerTwo: "The nearest positioned ancestor",
    answerThree: "The browser viewport",
    answerFour: "The <body> element's padding box",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 102,
    category: "CSS",
    question: "How does position: sticky behave?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "Identical to position: fixed",
    answerTwo: "It scrolls normally until it hits its offset, then sticks in place within its container",
    answerThree: "It pins the element to the bottom of the page",
    answerFour: "It disables scrolling on the element",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 103,
    category: "CSS",
    question: "What does z-index control?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "The stacking order of overlapping elements",
    answerTwo: "The zoom level of an element",
    answerThree: "The element's distance from the left edge",
    answerFour: "The rendering speed of an element",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 104,
    category: "CSS",
    question: "In flexbox, what does justify-content control?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "Alignment along the cross axis",
    answerTwo: "Alignment and spacing along the main axis",
    answerThree: "The text justification inside each item",
    answerFour: "The order of the flex items",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 105,
    category: "CSS",
    question: "In flexbox, what does align-items control?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "Alignment along the cross axis",
    answerTwo: "Alignment along the main axis",
    answerThree: "The gap between items",
    answerFour: "Whether items can wrap",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 106,
    category: "CSS",
    question: "What does flex-direction: column do?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "Splits the container into newspaper-style columns",
    answerTwo: "Reverses the order of the items",
    answerThree: "Makes the main axis vertical so items stack top to bottom",
    answerFour: "Centers all items horizontally",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 107,
    category: "CSS",
    question: "Which property defines the columns of a CSS grid?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "grid-template-columns",
    answerTwo: "grid-columns",
    answerThree: "column-count",
    answerFour: "grid-layout",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 108,
    category: "CSS",
    question: "In CSS grid, what does the fr unit represent?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "A fixed 16-pixel frame",
    answerTwo: "A fraction of the available space in the grid container",
    answerThree: "The font-size of the root element",
    answerFour: "One frame per second of animation",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 109,
    category: "CSS",
    question: "What is 1rem relative to?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "The root element's font size",
    answerTwo: "The parent element's font size",
    answerThree: "The viewport width",
    answerFour: "Always exactly 16 pixels, regardless of settings",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 110,
    category: "CSS",
    question: "When used on the font-size property, what is 1.5em relative to?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "The root element's font size",
    answerTwo: "The viewport height",
    answerThree: "The parent element's font size",
    answerFour: "The browser's default of exactly 10px",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 111,
    category: "CSS",
    question: "An element has width: 50%. Fifty percent of what?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "The viewport width",
    answerTwo: "Its containing block's (usually the parent's) width",
    answerThree: "Its own height",
    answerFour: "The screen resolution",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 112,
    category: "CSS",
    question: "What does 1vh equal?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "1% of the viewport height",
    answerTwo: "1% of the parent's height",
    answerThree: "1 vertical pixel",
    answerFour: "The height of one line of text",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 113,
    category: "CSS",
    question: "Which is a valid media query for screens 600px wide or narrower?",
    correctAnswerArray: [false, false, false, true, false],
    answerOne: "@screen (max-width: 600px) {}",
    answerTwo: "@media screen-size < 600px {}",
    answerThree: "@query (width <= 600px) {}",
    answerFour: "@media (max-width: 600px) {}",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 114,
    category: "CSS",
    question: "What does the :hover pseudo-class target?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "An element while the pointer is over it",
    answerTwo: "An element that has been clicked",
    answerThree: "The first element of its type",
    answerFour: "An element with keyboard focus",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 115,
    category: "CSS",
    question: "What does the ::before pseudo-element do?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "Selects the previous sibling element",
    answerTwo: "Inserts generated content as the first child of the element",
    answerThree: "Runs styles before the page loads",
    answerFour: "Targets the element's opening tag",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 116,
    category: "CSS",
    question: "What does the selector .card target?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "The element with id 'card'",
    answerTwo: "All <card> elements",
    answerThree: "All elements with class 'card'",
    answerFour: "The first element named 'card'",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 117,
    category: "CSS",
    question: "What does the selector #header target?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "The element with id 'header'",
    answerTwo: "All elements with class 'header'",
    answerThree: "All <header> elements",
    answerFour: "Every heading element on the page",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 118,
    category: "CSS",
    question: "What does the selector 'nav a' target?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "Only <a> elements that are direct children of <nav>",
    answerTwo: "All <a> elements anywhere inside a <nav>",
    answerThree: "<nav> elements inside an <a>",
    answerFour: "Both <nav> and <a> elements",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 119,
    category: "CSS",
    question: "How does 'ul > li' differ from 'ul li'?",
    correctAnswerArray: [false, false, false, true, false],
    answerOne: "There is no difference",
    answerTwo: "'ul > li' matches all nested list items at any depth",
    answerThree: "'ul > li' is invalid syntax",
    answerFour: "'ul > li' matches only direct children; 'ul li' matches any depth",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 120,
    category: "CSS",
    question: "What does !important do?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "Forces a declaration to win over normal specificity rules",
    answerTwo: "Marks a style for code review",
    answerThree: "Loads the rule before all others",
    answerFour: "Prevents the style from being inherited",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 121,
    category: "CSS",
    question: "Which of these properties is inherited by child elements by default?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "margin",
    answerTwo: "border",
    answerThree: "color",
    answerFour: "padding",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 122,
    category: "CSS",
    question: "How do you horizontally center a block element that has a set width?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "text-align: center on the element",
    answerTwo: "margin: 0 auto",
    answerThree: "align: center",
    answerFour: "position: center",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 123,
    category: "CSS",
    question: "What does overflow: hidden do?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "Clips any content that extends beyond the element's box",
    answerTwo: "Hides the entire element",
    answerThree: "Adds scrollbars to the element",
    answerFour: "Prevents the element from being inspected",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 124,
    category: "CSS",
    question: "What does the transition property do?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "Instantly swaps between two layouts",
    answerTwo: "Animates property changes smoothly over a duration",
    answerThree: "Moves the element to a new position permanently",
    answerFour: "Preloads the element's hover state",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 125,
    category: "CSS",
    question: "What is the valid range of the opacity property?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "0 to 100",
    answerTwo: "1 to 10",
    answerThree: "0 to 1",
    answerFour: "-1 to 1",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  // ---------- React ----------
  {
    questionNumber: 126,
    category: "React",
    question: "What is JSX?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "A syntax extension that compiles to JavaScript function calls",
    answerTwo: "A templating language that runs in the browser as-is",
    answerThree: "A CSS preprocessor for React",
    answerFour: "A JSON-based configuration format",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 127,
    category: "React",
    question: "What must a component's JSX return be wrapped in?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "A <div> — nothing else is allowed",
    answerTwo: "A single root element or a Fragment",
    answerThree: "A <root> element",
    answerFour: "Nothing — any number of top-level siblings is fine",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 128,
    category: "React",
    question: "What is the purpose of a Fragment (<>...</>)?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "Grouping children without adding an extra node to the DOM",
    answerTwo: "Splitting a component across multiple files",
    answerThree: "Lazy-loading part of the UI",
    answerFour: "Marking code that only runs in development",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 129,
    category: "React",
    question: "Which statement about props is true?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "A component should modify its props to update the UI",
    answerTwo: "Props persist between page reloads",
    answerThree: "Props are read-only inputs passed down from the parent",
    answerFour: "Props can only be strings",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 130,
    category: "React",
    question: "What does useState return?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "Just the current state value",
    answerTwo: "An array with the current value and an updater function",
    answerThree: "An object with get() and set() methods",
    answerFour: "A promise that resolves to the state",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 131,
    category: "React",
    question: "What causes a React component to re-render?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "A change in its state or the props it receives",
    answerTwo: "Any variable inside the component changing",
    answerThree: "Only calling forceUpdate()",
    answerFour: "Any DOM event anywhere on the page",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 132,
    category: "React",
    question: "When does useEffect with an empty dependency array ([]) run?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "On every render",
    answerTwo: "Never",
    answerThree: "Once, after the component's initial render",
    answerFour: "Before the component renders for the first time",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 133,
    category: "React",
    question: "When does the cleanup function returned from useEffect run?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "Only if the effect throws an error",
    answerTwo: "Before the effect runs again and when the component unmounts",
    answerThree: "On every click event",
    answerFour: "It never runs automatically",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 134,
    category: "React",
    question: "Why does React need a key prop when rendering a list?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "To identify which items changed, were added, or removed between renders",
    answerTwo: "To encrypt each list item",
    answerThree: "To set the tab order of the items",
    answerFour: "Keys are purely decorative",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 135,
    category: "React",
    question: "Why is using the array index as a key discouraged for lists that change?",
    correctAnswerArray: [false, false, false, true, false],
    answerOne: "Indexes are slower for React to read",
    answerTwo: "Indexes can exceed the maximum key length",
    answerThree: "It throws a warning in production builds",
    answerFour: "Reordering or removing items can mismatch state with the wrong item",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 136,
    category: "React",
    question: "What is a controlled component?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "A component that cannot receive props",
    answerTwo: "A form input whose value is driven by React state",
    answerThree: "A component wrapped in React.memo",
    answerFour: "A component rendered by the server",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 137,
    category: "React",
    question: "What does 'lifting state up' mean?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "Moving shared state to the closest common ancestor of the components that need it",
    answerTwo: "Storing state in localStorage instead of memory",
    answerThree: "Converting state into props",
    answerFour: "Moving state into the global window object",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 138,
    category: "React",
    question: "What is useRef commonly used for?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "Triggering a re-render when its value changes",
    answerTwo: "Fetching data on mount",
    answerThree: "Holding a mutable value or DOM reference that persists across renders without causing re-renders",
    answerFour: "Defining global constants",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 139,
    category: "React",
    question: "What problem does useContext solve?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "It memoizes expensive calculations",
    answerTwo: "It lets components read shared values without passing props through every level",
    answerThree: "It synchronizes state with the URL",
    answerFour: "It replaces the need for useState entirely",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 140,
    category: "React",
    question: "In JSX, what does {isLoggedIn && <Dashboard />} render when isLoggedIn is true?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "The <Dashboard /> component",
    answerTwo: "The string 'true'",
    answerThree: "Nothing — && is not valid in JSX",
    answerFour: "Both isLoggedIn and the component",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 141,
    category: "React",
    question: "How are event handlers named in JSX?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "Lowercase, like onclick",
    answerTwo: "camelCase, like onClick",
    answerThree: "With a handle- prefix, like handle-click",
    answerFour: "With data attributes, like data-click",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 142,
    category: "React",
    question: "Which attribute sets a CSS class on a JSX element?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "className",
    answerTwo: "class",
    answerThree: "cssClass",
    answerFour: "styleClass",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 143,
    category: "React",
    question: "What is useMemo for?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "Persisting state between page loads",
    answerTwo: "Memoizing entire components",
    answerThree: "Caching the result of an expensive calculation until its dependencies change",
    answerFour: "Storing form input values",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 144,
    category: "React",
    question: "What is useCallback for?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "Calling an API when the component mounts",
    answerTwo: "Keeping the same function reference between renders until its dependencies change",
    answerThree: "Converting callbacks into promises",
    answerFour: "Delaying a function call by one render",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 145,
    category: "React",
    question: "What is the virtual DOM?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "An in-memory representation of the UI that React diffs to compute minimal real DOM updates",
    answerTwo: "A backup copy of the page stored on the server",
    answerThree: "A browser feature React enables for speed",
    answerFour: "The DOM rendered inside an iframe",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 146,
    category: "React",
    question: "What do React.lazy and Suspense enable together?",
    correctAnswerArray: [false, false, false, true, false],
    answerOne: "Server-side rendering",
    answerTwo: "Automatic error boundaries",
    answerThree: "Lazy state initialization",
    answerFour: "Code splitting — loading a component's code only when it is first rendered",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 147,
    category: "React",
    question: "What does StrictMode do?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "Enforces TypeScript across the app",
    answerTwo: "Runs extra development-only checks and warnings; it has no effect in production",
    answerThree: "Blocks all deprecated browser APIs",
    answerFour: "Makes state immutable at runtime",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 148,
    category: "React",
    question: "Which is a rule of hooks?",
    correctAnswerArray: [true, false, false, false, false],
    answerOne: "Only call hooks at the top level — never inside loops, conditions, or nested functions",
    answerTwo: "Hooks must be called inside a try/catch block",
    answerThree: "A component may use at most five hooks",
    answerFour: "Hooks can only be used in class components",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 149,
    category: "React",
    question: "What is prop drilling?",
    correctAnswerArray: [false, false, true, false, false],
    answerOne: "Mutating props inside a child component",
    answerTwo: "Generating props dynamically at runtime",
    answerThree: "Passing props through many intermediate components that don't use them",
    answerFour: "Validating props with PropTypes",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
  {
    questionNumber: 150,
    category: "React",
    question: "What is a custom hook?",
    correctAnswerArray: [false, true, false, false, false],
    answerOne: "Any function defined inside a component",
    answerTwo: "A reusable function whose name starts with 'use' and that can call other hooks",
    answerThree: "A React plugin installed from npm",
    answerFour: "A hook that overrides React's built-in hooks",
    timesCorrect: 0,
    timesIncorrect: 0,
  },
];

module.exports = questionData;
